apiVersion: apache.sdk.operator-framework.io/v1
kind: Tomcat
metadata:
  name: tomcat-sample
spec:
  replicaCount: 1
  image:
    tomcat:
      repository: tomcat
      tag: "7.0"
  
  service:
    name: http
    type: LoadBalancer
    externalPort: 80
    internalPort: 8080
  
  hostPort: 8009
